//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pelicula
    {
        public int Id { get; set; }
        public string Portada { get; set; }
        public string Titulo { get; set; }
        public string Director { get; set; }
        public string Descripcion { get; set; }
        public string Actores { get; set; }
        public int Año { get; set; }
    }
}
